In [ ]:
## 00. Pytorch Fundamentals

In [ ]:
!nvidia-smi

Sat Sep 30 10:18:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


Introduction to tensors

In [ ]:
## creating tensors-https://pytorch.org/docs/stable/tensors.html
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # a scalar has no dimensions

0

In [ ]:
scalar.item() # get tensor back as python int

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # number of square bracket pairs

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,0],[23,1,98],[24,99,22]]])
TENSOR

tensor([[[ 1,  2,  0],
         [23,  1, 98],
         [24, 99, 22]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  0],
        [23,  1, 98],
        [24, 99, 22]])

In [ ]:
TENSOR[0][1]

tensor([23,  1, 98])

### Random tensors

# Why random tensors?
Randomntensors are important beacsue the way many neural networks learn is that they start with  tensors full of random data and then adjst those random numbers to better represent the data.

start with random number --> look at data --> update random numbers --> look at data --> update random numbers

https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8086, 0.6624, 0.4188, 0.0319],
        [0.7433, 0.7610, 0.2461, 0.1514],
        [0.6796, 0.2798, 0.7210, 0.3652]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [ ]:
random_tensor1 = torch.rand(1,3,4)
random_tensor1

tensor([[[0.9273, 0.2004, 0.4053, 0.4373],
         [0.3562, 0.2947, 0.2900, 0.4149],
         [0.5215, 0.3371, 0.5662, 0.3435]]])

In [ ]:
# create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channel-rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, colour channel-rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# colour channels will remain as 3

In [ ]:
random_ten = torch.rand(size =(2,3,4,1))

In [ ]:
random_ten

tensor([[[[0.9593],
          [0.7355],
          [0.0362],
          [0.3379]],

         [[0.3003],
          [0.4326],
          [0.5858],
          [0.4996]],

         [[0.7490],
          [0.8281],
          [0.3743],
          [0.0506]]],


        [[[0.9649],
          [0.1015],
          [0.4819],
          [0.9251]],

         [[0.4520],
          [0.3584],
          [0.1824],
          [0.8030]],

         [[0.4983],
          [0.1386],
          [0.4183],
          [0.0913]]]])

In [ ]:
random_ten

tensor([[[0.6758, 0.1061, 0.3246, 0.4299],
         [0.2265, 0.5726, 0.9961, 0.9205],
         [0.0754, 0.7630, 0.5031, 0.9640]],

        [[0.8173, 0.2699, 0.7433, 0.8217],
         [0.3380, 0.1836, 0.6503, 0.7422],
         [0.9478, 0.7201, 0.7724, 0.5708]]])

# zeros and ones

In [ ]:
# create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype, zeros.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32, torch.float32)

# Creating range of tensors and tensor-like

In [ ]:
# torch.range()
torch.range(0,10)

<ipython-input-52-a8f1092a23a6>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#because of warning
one_to_ten = torch.arange(start = 0,end=1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# creating tensors like
# replicate the tensor, without knowing shape
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor dtype

In [ ]:
# float 32 - default
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
1. Tensors not right data type - to get dtype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from tensor, can use `tensor.device`

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16, # multiple options, check doc
                               device=None, # what device is your tensor on - by default ' cpu', can change to 'cuda'
                               requires_grad=False) # if you wnat pytorch ton keep track of gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# data type are related to precision. is a measure of how much detail a quantitiy is expressed

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # multiple options, check doc
                               device=None, # what device is your tensor on - by default ' cpu', can change to 'cuda'
                               requires_grad=False)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)# convert float 32 to float 16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
long_tensor = torch.tensor([3,6,9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [ ]:
long_tensor*float_32_tensor

tensor([ 9., 36., 81.])

with 3 big errors

In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)
print(some_tensor.size())

tensor([[0.5723, 0.0464, 0.4275, 0.1198],
        [0.1272, 0.2808, 0.9211, 0.3073],
        [0.8053, 0.8920, 0.8560, 0.8942]])
torch.float32
torch.Size([3, 4])
cpu
torch.Size([3, 4])


# Manipulating tensors(tensor operations)
Tensor operations include:
1. addition
2. subtraction
3. multiplication (element-wise)
4. division
5. matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# inbuilt pytorch functions

In [ ]:
torch.mul(tensor,10), torch.add(tensor,10), torch.sub(tensor,10),torch.div(tensor,10)

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]))

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning
1. Element wise
2. Matrix multiplication- dot product

In [ ]:
# element eise
print(tensor, "*", tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor) # 1*1 + 2*2 + 3*3

tensor(14)

pytorch implementation is usually very fast

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.26 ms, sys: 1.08 ms, total: 2.34 ms
Wall time: 1.93 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 313 µs, sys: 27 µs, total: 340 µs
Wall time: 209 µs


tensor(14)

One of the main errors in DL is shape error.

The two main rules that matrix multiplication needs to satisfy:
1. The inner dimensions must match:
  * (3,2) & (3,2) won't work
  * (3,2) & (2,3) will work
2. The resulting matrix has shape of outer dimensions.

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(2,3))

RuntimeError: ignored

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.2142, 0.6137],
        [0.4018, 0.9653]])

In [ ]:
# shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
# torch.mm(tensor_A, tensor_B) tensor.mm is same as tensor.matmul (alias)
torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issues, we can manipulate one of the tensor shape with transpose.
Transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

In [ ]:
#matrixmultiplication.xyz

Finding the mean, max, min, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), x.max(), torch.min(x), x.min()

(tensor(90), tensor(90), tensor(0), tensor(0))

In [ ]:
torch.mean(x) # ERROR: tensor not of right datatype
# some pytorch functions are not suitable for few data types

RuntimeError: ignored

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

Helpful when we run the softmax function later on

In [ ]:
x.argmin(), x[0], x.argmax(), x[9]

(tensor(0), tensor(0), tensor(9), tensor(90))

# Reshaping, stacking, squeezing and unsqueezing tensors

* reshaping - reshapes input tensor to a defined shape
* view - return the view of an input tensor in a certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (stack)
  * stack(dim)
  * vstack
  * hstack
* squeeze - removes all `1` dimensions from a tensor
* unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a a view of the input tensor with dimensions permuted (swapped) in a certain way

In [ ]:
# reshape - add an extra dimension
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape
# error because 9 elementscannot be squeezed into 7; even (2,10) will give an error

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape
# added a square bracket

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# changing z changes x because a view of the tensor shared the same memory as the original tensor
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x]) # dim=0 by default
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# squeeze & unsqueeze
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
x_squeeze = torch.squeeze(x)
x_squeeze

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x_squeeze.shape

torch.Size([10])

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
squeeze = torch.squeeze(x)
x_squeeze, x_squeeze.shape # outer square bracket removed (if dimensionality is(1,9,1), it will remove all 1s)

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
temp = torch.rand(2,1,3,4,1,1)
temp, temp.shape

(tensor([[[[[[0.7635]],
 
            [[0.5985]],
 
            [[0.3672]],
 
            [[0.6263]]],
 
 
           [[[0.1232]],
 
            [[0.5060]],
 
            [[0.6654]],
 
            [[0.3987]]],
 
 
           [[[0.8936]],
 
            [[0.8218]],
 
            [[0.4067]],
 
            [[0.1380]]]]],
 
 
 
 
         [[[[[0.1919]],
 
            [[0.5070]],
 
            [[0.9139]],
 
            [[0.6566]]],
 
 
           [[[0.0715]],
 
            [[0.2411]],
 
            [[0.7330]],
 
            [[0.9727]]],
 
 
           [[[0.9289]],
 
            [[0.2268]],
 
            [[0.0575]],
 
            [[0.2073]]]]]]),
 torch.Size([2, 1, 3, 4, 1, 1]))

In [ ]:
temp.squeeze(), temp.squeeze().shape

(tensor([[[0.7635, 0.5985, 0.3672, 0.6263],
          [0.1232, 0.5060, 0.6654, 0.3987],
          [0.8936, 0.8218, 0.4067, 0.1380]],
 
         [[0.1919, 0.5070, 0.9139, 0.6566],
          [0.0715, 0.2411, 0.7330, 0.9727],
          [0.9289, 0.2268, 0.0575, 0.2073]]]),
 torch.Size([2, 3, 4]))

In [ ]:
# unsqueeze  - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [ ]:
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")
x_unsqueezed = x_squeeze.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [ ]:
# permute- rearrange?
# swap the order
x_original = torch.rand(size = (224,224,3)) # [height, width, color channels]
x_permuted = x_original.permute(2,0,1)
print(f"Previous tensor shape: {x_original.shape}")
print(f"New tensor shape: {x_permuted.shape}") # [color channels, height, width]

Previous tensor shape: torch.Size([224, 224, 3])
New tensor shape: torch.Size([3, 224, 224])


In [ ]:
x_original = torch.rand(size = (224,224,3,33))
x_permuted = x_original.permute(2,3, 0,1)
print(f"Previous tensor shape: {x_original.shape}")
print(f"New tensor shape: {x_permuted.shape}")

Previous tensor shape: torch.Size([224, 224, 3, 33])
New tensor shape: torch.Size([3, 33, 224, 224])


In [ ]:
# permute is also a view
x_original[0,0,0] = 33

In [ ]:
x_permuted[0,0,0]

tensor(33.)

# Indexing (selecting data from tensors)
Indexing with PyTorch us similar to indexing in NumPy

In [ ]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket , dim =1
x[0][0]

tensor([1, 2, 3])

In [ ]:
# index on the inner most bracket, last dim
x[0][0][0]

tensor(1)

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[1][1][1]

IndexError: ignored

In [ ]:
#get number 9
x[0][2][2]

tensor(9)

In [ ]:
#use : to select all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of second dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of the 0 dim but only 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#get index 0 of 0th and 1st dim and all values of second dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index on x to get 9, index on x to get 3,6,9
x[0,2,2], x[:,:,2]

(tensor(9), tensor([[3, 6, 9]]))

# PyTorch tensors and NumPy

Numpy - scientific python numerical computing library, popular.
Pytorch has interaction ability with numpy
* start with Data in numpy, want to change to tensor -> `torch.from_numpy(ndarray)`
* pytorch tensor -> numpy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # default value of numpy is float64 and tensor is float32

dtype('float64')

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [ ]:
# warning: by default while converting from numpy->pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

In [ ]:
#change the value of array, what will happen to tensor
array = array+1
array, tensor # means tensor is created in another memory location independent of numpy array

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,tensor.dtype, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to numpy
tensor = tensor-1
tensor, numpy_tensor

(tensor([0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

In short how NN learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

* with each torch.rand, a new tensor is formed. Sometimes you don't want that much randomness.
* To reduce randomness in NN and PyTorch, comes the concept of `random seed`
* Essentially what a random seed dows is "flavour" the randomness - not true randomness
* computers are fundamentally deterministic, they run the same steps again and again, so the randomness we talk about is pseudorandomness or generated randomness. Random seed flavours that randomness


In [ ]:
torch.rand(3,3)

tensor([[0.4374, 0.4056, 0.9503],
        [0.0075, 0.9315, 0.4429],
        [0.1086, 0.9594, 0.4898]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.9799, 0.0763, 0.9904, 0.1005],
        [0.8254, 0.2869, 0.3636, 0.7711],
        [0.6412, 0.3992, 0.6843, 0.3253]])
tensor([[0.0173, 0.0498, 0.3362, 0.2825],
        [0.1914, 0.2907, 0.8014, 0.7060],
        [0.6987, 0.8604, 0.3504, 0.8612]])


In [ ]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
RANDOM_SEED = 42 #any number
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42 #any number but 42 is used mostly
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) # call maual seed everytime you call .rand method or any sort of randomness
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Different ways of accessing GPU in PyTorch

* tensors and pytorch objects on GPUs for faster computations
* GPUs mean faster computation on numbers, thanks to CUDA, NVIDIA hardware and PyTorch working BTS

In [ ]:
# Getting a GPU, change runtime to GPU, otherwise
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi # after runtime change to GPU

Sat Sep 30 18:24:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
## check for gpu access with pytorch
import torch

In [ ]:
torch.cuda.is_available() # cuda is nvidia's programming interface that allows us to use gpu for numerical computing

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

In [ ]:
# since pytorch is capable to run on CPU/GPU, it is good to run device agnostic code

# Putting tensors and models on GPU

The reasons -
* because GPU results in faster computations

In [ ]:
# create a tensor - default on CPU
tensor = torch.tensor([1,2,3], device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Transfer tensor to GPU using device that we had set earlier using device agnostic code
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
# moving tensor back to cpu
# if tensor is on gpu cannot transfer to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# to fix the gpu tensor with numpy, set it to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu # remains unchanged

tensor([1, 2, 3], device='cuda:0')

# Exercise and extra-curriculum

In [ ]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [ ]:
x.pow(2), x.pow(2).sum()


(tensor([[1., 1.],
         [1., 1.]], grad_fn=<PowBackward0>),
 tensor(4., grad_fn=<SumBackward0>))

In [ ]:
out = x.pow(2).sum()

In [ ]:
out.backward()

In [ ]:
x.grad

tensor([[ 4., -4.],
        [ 4.,  4.]])

2. Create a random tensor with shape (7, 7).


In [ ]:
tensor = torch.rand(7,7)
tensor

tensor([[0.3145, 0.1588, 0.5928, 0.8337, 0.6662, 0.2565, 0.5485],
        [0.3089, 0.1683, 0.2440, 0.6322, 0.2666, 0.0198, 0.0030],
        [0.6091, 0.0642, 0.2760, 0.0026, 0.7427, 0.9521, 0.1284],
        [0.7835, 0.2354, 0.1114, 0.5001, 0.5649, 0.9849, 0.3599],
        [0.4126, 0.6977, 0.8155, 0.8900, 0.1734, 0.3398, 0.3264],
        [0.2386, 0.0468, 0.2694, 0.4313, 0.8325, 0.8128, 0.5104],
        [0.2480, 0.1983, 0.9089, 0.9151, 0.7288, 0.2253, 0.7856]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
torch.matmul(tensor, torch.rand(1,7).T)

tensor([[1.6919],
        [0.6822],
        [1.8936],
        [2.3177],
        [1.8622],
        [1.8675],
        [2.0064]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [ ]:
RANDOM_SEED = 0 #any number but 42 is used mostly
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7).T
torch.matmul(tensor, tensor2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.


In [34]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [37]:
torch.manual_seed(1234)
x = torch.rand(2,3)
torch.manual_seed(1234)
y = torch.rand(2,3)
x,y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [36]:
!nvidia-smi

Sat Sep 30 19:03:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    29W /  70W |    601MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [38]:
x_gpu , y_gpu = x.to(device), y.to(device)
x_gpu , y_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [39]:
x_gpu.shape, y_gpu.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [40]:
torch.mm(x_gpu,y_gpu.T)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.

In [42]:
tensor = torch.mm(x_gpu,y_gpu.T)
torch.max(tensor), torch.min(tensor)

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [43]:
torch.argmax(tensor), torch.argmin(tensor)

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [50]:
tensor[0][1]

tensor(0.2161, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [51]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
